### ISSUE TITLE
feat(telemetry): implement telemetry for aggregator

### ISSUE THREAD

**Issue by JuArce** [yetanotherco/aligned_layer#1075]
# Description
This issue supersedes #936 

The aggregator has to communicate to the telemetry_api using HTTP endpoints
The telemetry_api will handle traces creation

# Tasks

- [x] Docker compose with Otel Collector and Jaeger UI
- [x] Init traces on NewTask
- [x] Add span on Operator responses
- [x]  Add span on Quorum Reached
- [x] Add span on Tasks errors (ie task expired)
- [x] Close traces after a period of time the quorum was reached to wait for most operators responses
