### ISSUE TITLE
feat(telemetry): keep tracking of registered operators

### ISSUE THREAD

**Issue by JuArce** [yetanotherco/aligned_layer#1076]
# Description

Telemetry API has to keep tracking of registered operators and maintain in a database the following information
- Operator address
- Operator ID
- Stake
- Name

# Tasks

- [x] Get list of operators on startup
- [x] Get operators metadata
- [x] Listen for new operators registration/deregistration
- [x] Listen for changes on operators stake
- [ ] Listen for changes on operators metadata
