### ISSUE TITLE
feat (Light Client): Implement Light Clients

### ISSUE THREAD

**Issue by NicolasRampoldi** [yetanotherco/aligned_layer#179]
# Tasks

# CLI

- [x] Get batch of proofs from S3 bucket.
- [x] Select one random proof.
- [x] Verify that proof using SP1.
- [ ] Modify getting batch of proofs from S3 bucket to querying the event from Ethereum and using that URL to fetch the batch.
- [ ] Verify any kind of proof
- [ ] Verify the whole batch 
- [ ] Send result to backend
- [ ] Require an Eth account with 0.001 Ethereum
- [ ] Sign the root of the batch with Eth account 

# Backend

- [ ] Store responded verification by address, with batch and index of proof
- [ ] Add a step to register a client 
- [ ] Limit registered clients to 1k
- [ ] Check signature 
- [ ] Self update
