### ISSUE TITLE
feat (operator): implement merkle root ffi

### ISSUE THREAD

**Issue by NicolasRampoldi** [yetanotherco/aligned_layer#186]
# TODO:

- [x] **In Rust:** Deserialize bytes from the batch.
- [x] **In Rust:** Calculate merkle root of the batch.
- [x] **In Rust:** Compare with the given merkle root.
- [ ] **In Go:** Implement binding.
