### ISSUE TITLE
docs: add operator registration instructions 

### ISSUE THREAD

**Issue by NicolasRampoldi** [yetanotherco/aligned_layer#372]
# Description

- We should add operator registration instructions, so that whitelisted addresses can register their operators on Aligned.

# TODO
- [x] Register operator on EigenLayer.
- [x] Register operator on Aligned.
- [x] Run operator binary.
- [x] Upgrade binary.
