### ISSUE TITLE
feat: add install aligned operator

### ISSUE THREAD

**Issue by NicolasRampoldi** [yetanotherco/aligned_layer#379]
# TODO

- [ ] Add script to download operator binary from release.
- [ ] Add script to upload operator binary on release.
- [ ] Change README to use downloaded operator binary.

**Comment by NicolasRampoldi** [comment]
Doesn't work due to ffi's.
