### ISSUE TITLE
Before mainnet checklist

### ISSUE THREAD

**Issue by entropidelic** [yetanotherco/aligned_layer#525]
- [x] add max value for user balances in batcher payment system
- [x] delete task sender
- [x] reorder aligned struct params #517
