### ISSUE TITLE
chore(telemetry): add operators information to responses spans

### ISSUE THREAD

**Issue by JuArce** [yetanotherco/aligned_layer#961]
# Description

Add the following data to the responses spans
- Operator address
- Operator address

On aggregator start, load all operators data and keep tracking of updates. This way, traces can have information about operator that did not respond to a task

# Tasks

- [x] Get list of all operators registered to the AVS
- [x] Get metadata of all operators registered to the AVS
- [x] Show operators data on responses spans
- [x] Update operators lists on new events
